/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Decision from './Decision';
import State from './State';





/**
* The Action model module.
* @module model/Action
* @version 1.0.0
*/
export default class Action {
    /**
    * Constructs a new <code>Action</code>.
    * @alias module:model/Action
    * @class
    * @param processedBy {String} Person to process the action
    */

    constructor(processedBy) {
        

        
        

        this['processed_by'] = processedBy;

        
    }

    /**
    * Constructs a <code>Action</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Action} obj Optional instance to populate.
    * @return {module:model/Action} The populated <code>Action</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Action();

            
            
            

            if (data.hasOwnProperty('processed_by')) {
                obj['processed_by'] = ApiClient.convertToType(data['processed_by'], 'String');
            }
            if (data.hasOwnProperty('actioned_at')) {
                obj['actioned_at'] = ApiClient.convertToType(data['actioned_at'], 'Date');
            }
            if (data.hasOwnProperty('notified_at')) {
                obj['notified_at'] = ApiClient.convertToType(data['notified_at'], 'Date');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = State.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('decision')) {
                obj['decision'] = Decision.constructFromObject(data['decision']);
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
        }
        return obj;
    }

    /**
    * Person to process the action
    * @member {String} processed_by
    */
    processed_by = undefined;
    /**
    * Timestamp of action be processed
    * @member {Date} actioned_at
    */
    actioned_at = undefined;
    /**
    * Timestamp of action be notified
    * @member {Date} notified_at
    */
    notified_at = undefined;
    /**
    * @member {module:model/State} state
    */
    state = undefined;
    /**
    * @member {module:model/Decision} decision
    */
    decision = undefined;
    /**
    * Comments about the action
    * @member {String} comments
    */
    comments = undefined;








}


