/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Group model module.
* @module model/Group
* @version 1.0.0
*/
export default class Group {
    /**
    * Constructs a new <code>Group</code>.
    * @alias module:model/Group
    * @class
    * @param name {String} Group name
    * @param contactMethod {String} Contact type
    * @param contactSetting {String} Settings of contact
    */

    constructor(name, contactMethod, contactSetting) {
        

        
        

        this['name'] = name;this['contact_method'] = contactMethod;this['contact_setting'] = contactSetting;

        
    }

    /**
    * Constructs a <code>Group</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Group} obj Optional instance to populate.
    * @return {module:model/Group} The populated <code>Group</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Group();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('contact_method')) {
                obj['contact_method'] = ApiClient.convertToType(data['contact_method'], 'String');
            }
            if (data.hasOwnProperty('contact_setting')) {
                obj['contact_setting'] = ApiClient.convertToType(data['contact_setting'], 'String');
            }
        }
        return obj;
    }

    /**
    * Group name
    * @member {String} name
    */
    name = undefined;
    /**
    * Contact type
    * @member {String} contact_method
    */
    contact_method = undefined;
    /**
    * Settings of contact
    * @member {String} contact_setting
    */
    contact_setting = undefined;








}


