/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Decision from './Decision';
import State from './State';





/**
* The Request model module.
* @module model/Request
* @version 1.0.0
*/
export default class Request {
    /**
    * Constructs a new <code>Request</code>.
    * @alias module:model/Request
    * @class
    * @param requester {String} Requester info
    * @param name {String} Request name
    * @param content {String} Request content
    */

    constructor(requester, name, content) {
        

        
        

        this['requester'] = requester;this['name'] = name;this['content'] = content;

        
    }

    /**
    * Constructs a <code>Request</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Request} obj Optional instance to populate.
    * @return {module:model/Request} The populated <code>Request</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Request();

            
            
            

            if (data.hasOwnProperty('requester')) {
                obj['requester'] = ApiClient.convertToType(data['requester'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = State.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('decision')) {
                obj['decision'] = Decision.constructFromObject(data['decision']);
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }

    /**
    * Requester info
    * @member {String} requester
    */
    requester = undefined;
    /**
    * Request name
    * @member {String} name
    */
    name = undefined;
    /**
    * Request description
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {module:model/State} state
    */
    state = undefined;
    /**
    * @member {module:model/Decision} decision
    */
    decision = undefined;
    /**
    * Comments for requests
    * @member {String} reason
    */
    reason = undefined;
    /**
    * Request content
    * @member {String} content
    */
    content = undefined;








}


