/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Decision from './Decision';
import State from './State';





/**
* The Stage model module.
* @module model/Stage
* @version 1.0.0
*/
export default class Stage {
    /**
    * Constructs a new <code>Stage</code>.
    * @alias module:model/Stage
    * @class
    * @param groupId {Number} 
    */

    constructor(groupId) {
        

        
        

        this['group_id'] = groupId;

        
    }

    /**
    * Constructs a <code>Stage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Stage} obj Optional instance to populate.
    * @return {module:model/Stage} The populated <code>Stage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Stage();

            
            
            

            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Number');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = State.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('decision')) {
                obj['decision'] = Decision.constructFromObject(data['decision']);
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} group_id
    */
    group_id = undefined;
    /**
    * @member {module:model/State} state
    */
    state = undefined;
    /**
    * @member {module:model/Decision} decision
    */
    decision = undefined;
    /**
    * 
    * @member {String} comments
    */
    comments = undefined;








}


