/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* Enum class State.
* @enum {}
* @readonly
*/
export default class State {
    
        /**
         * value: "pending"
         * @const
         */
        pending = "pending";

    
        /**
         * value: "skipped"
         * @const
         */
        skipped = "skipped";

    
        /**
         * value: "notified"
         * @const
         */
        notified = "notified";

    
        /**
         * value: "finished"
         * @const
         */
        finished = "finished";

    

    /**
    * Returns a <code>State</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/State} The enum <code>State</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}


