/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Template model module.
* @module model/Template
* @version 1.0.0
*/
export default class Template {
    /**
    * Constructs a new <code>Template</code>.
    * @alias module:model/Template
    * @class
    * @param title {String} 
    */

    constructor(title) {
        

        
        

        this['title'] = title;

        
    }

    /**
    * Constructs a <code>Template</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Template} obj Optional instance to populate.
    * @return {module:model/Template} The populated <code>Template</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Template();

            
            
            

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {String} description
    */
    description = undefined;








}


