/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InsightsServiceApprovalApIs);
  }
}(this, function(expect, InsightsServiceApprovalApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InsightsServiceApprovalApIs.Request();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Request', function() {
    it('should create an instance of Request', function() {
      // uncomment below and update the code to test Request
      //var instane = new InsightsServiceApprovalApIs.Request();
      //expect(instance).to.be.a(InsightsServiceApprovalApIs.Request);
    });

    it('should have the property requester (base name: "requester")', function() {
      // uncomment below and update the code to test the property requester
      //var instane = new InsightsServiceApprovalApIs.Request();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new InsightsServiceApprovalApIs.Request();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new InsightsServiceApprovalApIs.Request();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new InsightsServiceApprovalApIs.Request();
      //expect(instance).to.be();
    });

    it('should have the property decision (base name: "decision")', function() {
      // uncomment below and update the code to test the property decision
      //var instane = new InsightsServiceApprovalApIs.Request();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instane = new InsightsServiceApprovalApIs.Request();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instane = new InsightsServiceApprovalApIs.Request();
      //expect(instance).to.be();
    });

  });

}));
