/**
 * Insights Service Approval APIs
 * APIs to query approval service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InsightsServiceApprovalApIs);
  }
}(this, function(expect, InsightsServiceApprovalApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InsightsServiceApprovalApIs.AdminsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminsApi', function() {
    describe('addAction', function() {
      it('should call addAction successfully', function(done) {
        //uncomment below and update the code to test addAction
        //instance.addAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addGroup', function() {
      it('should call addGroup successfully', function(done) {
        //uncomment below and update the code to test addGroup
        //instance.addGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addStage', function() {
      it('should call addStage successfully', function(done) {
        //uncomment below and update the code to test addStage
        //instance.addStage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addTemplate', function() {
      it('should call addTemplate successfully', function(done) {
        //uncomment below and update the code to test addTemplate
        //instance.addTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addWorkflow', function() {
      it('should call addWorkflow successfully', function(done) {
        //uncomment below and update the code to test addWorkflow
        //instance.addWorkflow(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchActionById', function() {
      it('should call fetchActionById successfully', function(done) {
        //uncomment below and update the code to test fetchActionById
        //instance.fetchActionById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchActions', function() {
      it('should call fetchActions successfully', function(done) {
        //uncomment below and update the code to test fetchActions
        //instance.fetchActions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchGroupById', function() {
      it('should call fetchGroupById successfully', function(done) {
        //uncomment below and update the code to test fetchGroupById
        //instance.fetchGroupById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchGroups', function() {
      it('should call fetchGroups successfully', function(done) {
        //uncomment below and update the code to test fetchGroups
        //instance.fetchGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchRequests', function() {
      it('should call fetchRequests successfully', function(done) {
        //uncomment below and update the code to test fetchRequests
        //instance.fetchRequests(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchStageById', function() {
      it('should call fetchStageById successfully', function(done) {
        //uncomment below and update the code to test fetchStageById
        //instance.fetchStageById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchStages', function() {
      it('should call fetchStages successfully', function(done) {
        //uncomment below and update the code to test fetchStages
        //instance.fetchStages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchTemplateById', function() {
      it('should call fetchTemplateById successfully', function(done) {
        //uncomment below and update the code to test fetchTemplateById
        //instance.fetchTemplateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchTemplateWorkflows', function() {
      it('should call fetchTemplateWorkflows successfully', function(done) {
        //uncomment below and update the code to test fetchTemplateWorkflows
        //instance.fetchTemplateWorkflows(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchTemplates', function() {
      it('should call fetchTemplates successfully', function(done) {
        //uncomment below and update the code to test fetchTemplates
        //instance.fetchTemplates(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchWorkflowById', function() {
      it('should call fetchWorkflowById successfully', function(done) {
        //uncomment below and update the code to test fetchWorkflowById
        //instance.fetchWorkflowById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchWorkflowRequests', function() {
      it('should call fetchWorkflowRequests successfully', function(done) {
        //uncomment below and update the code to test fetchWorkflowRequests
        //instance.fetchWorkflowRequests(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchWorkflows', function() {
      it('should call fetchWorkflows successfully', function(done) {
        //uncomment below and update the code to test fetchWorkflows
        //instance.fetchWorkflows(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeAction', function() {
      it('should call removeAction successfully', function(done) {
        //uncomment below and update the code to test removeAction
        //instance.removeAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeGroup', function() {
      it('should call removeGroup successfully', function(done) {
        //uncomment below and update the code to test removeGroup
        //instance.removeGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeRequest', function() {
      it('should call removeRequest successfully', function(done) {
        //uncomment below and update the code to test removeRequest
        //instance.removeRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeStage', function() {
      it('should call removeStage successfully', function(done) {
        //uncomment below and update the code to test removeStage
        //instance.removeStage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeTemplate', function() {
      it('should call removeTemplate successfully', function(done) {
        //uncomment below and update the code to test removeTemplate
        //instance.removeTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeWorkflow', function() {
      it('should call removeWorkflow successfully', function(done) {
        //uncomment below and update the code to test removeWorkflow
        //instance.removeWorkflow(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAction', function() {
      it('should call updateAction successfully', function(done) {
        //uncomment below and update the code to test updateAction
        //instance.updateAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateGroup', function() {
      it('should call updateGroup successfully', function(done) {
        //uncomment below and update the code to test updateGroup
        //instance.updateGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRequest', function() {
      it('should call updateRequest successfully', function(done) {
        //uncomment below and update the code to test updateRequest
        //instance.updateRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateStage', function() {
      it('should call updateStage successfully', function(done) {
        //uncomment below and update the code to test updateStage
        //instance.updateStage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTemplate', function() {
      it('should call updateTemplate successfully', function(done) {
        //uncomment below and update the code to test updateTemplate
        //instance.updateTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWorkflow', function() {
      it('should call updateWorkflow successfully', function(done) {
        //uncomment below and update the code to test updateWorkflow
        //instance.updateWorkflow(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
